package net.blixate.deadlight.kit.perks;

public enum PerkEventType {
	LOBBY_START, SURVIVOR_SPAWN, END_GAME_COLLAPSE_START,
	SURVIVOR_DEATH, SURVIVOR_HIT, SURVIVOR_FIRST_HIT, SURVIVOR_HEALTH_CHANGED, BLOOD_GAIN,
	OBJECTIVE_BREAK, LAST_OBJECTIVE, OBJECTIVE_COMPLETE,
	ALL_OBJECTIVES_COMPLETED, EXIT_PORTAL_OPENED, SURVIVOR_ESCAPE, SURVIVOR_HEAL,
	CROUCH, SPRINT, SURVIVOR_RIGHT_CLICK, KILLER_RIGHT_CLICK, LAST_SURVIVOR_ALIVE,
	PRESS_F, KILLER_PUNCH, KILLER_RIGHT_CLICK_SURVIVOR,
	PROTECTION_HIT, OBSESSION_HIT, REGRESSION_STOPPED, FATAL_HIT, SCORE_EVENT, SURVIVOR_REVIVE,
	SOUL_PICKUP, SOUL_PLACE, SOUL_DESTROY, ATTEMPT_PLAYER_HIT, USE_ITEM;
}
