package net.blixate.deadlight.player.stats;

public enum DeadlightStat {
	GAMES_PLAYED, //
	ESCAPES, KILLS, DEATHS,//
	OBSESSION_ESCAPES,//
	NO_OBJECTIVES_COMPLETED, //// Killer
	NO_ESCAPES,//X
	SURVIVORS_HIT,//X
	SCRUBBER_GAMES_PLAYED,//X
	HUNTER_GAMES_PLAYED,//X
	CLOAKER_GAMES_PLAYED,//X
	WARPER_GAMES_PLAYED,//X
	JACK_GAMES_PLAYED,//X
	VISITOR_GAMES_PLAYED,//X
	NECROMANCER_GAMES_PLAYED,//X
	SOULS_DESTROYED,//X
	FRAGMENTS_SABOTAGED,//
	END_GAME_KILLS,//
	ABILITY_KILLS,//
	EARLY_END_GAME,//
	ALL_SURVIVORS_HIT,//X
	HEALS_INTERRUPTED,//
	FLOWER_TOTEMS_DESTROYED,//
	REVIVES_GIVEN, REVIVES_RECEIVED,//// Survivor
	FRAGMENTS_COMPLETED,//
	ITEMS_USED,//
	HEALS_GIVEN, HEALS_RECEIVED,//
	REGRESSION_INTERRUPTS,//
	KILLER_RADIUS_TIME,//X
	UNTOUCHABLES,//X
	PROTECTION_HITS,//X
	DISTRACTIONS,//X
	END_GAME_REVIVES_GIVEN,//X
	FLOWER_UNDYING_SAVES,//X
}
